### ISSUE TITLE
Publish 0.5.2 to pub.dev

### ISSUE THREAD

**Issue by zmuranaka** [altera2015/usbserial#113]
[0.5.2](https://github.com/altera2015/usbserial/releases/tag/v0.5.2) is released but pub.dev only has 0.5.1.

As a workaround we currently have to do this:

```yaml
  usb_serial:
    git:
      url: https://github.com/altera2015/usbserial.git
```
